### PR TITLE
Add FX2-dev, opsis and atlys boards' lights support

### PR DESCRIPTION
**Pull request by paddatrapper**
Atlys is not added as the lighting pins are also used for JTAG communication

### CODE REVIEW

**Comment by mithro** [comment]
Why is the code for the FX1 so different to the others?

**Comment by mithro** [comment]
I don't get your comment about "lighting pins are also used for JTAG communication" bit?

**Comment by paddatrapper** [comment]
The FX1 code was what was originally there. I don't quite follow how they got the memory addresses they have, thus I'm not going to mess with it

**Comment by paddatrapper** [comment]
> I don't get your comment about "lighting pins are also used for JTAG communication" bit?

As discussed in IRC, this will change to LD14 and be included here

**Comment by paddatrapper** [comment]
Fixed

**Comment by mithro** [comment]
@paddatrapper I refactored the ifdefs in this file a little, PTAL and confirm this is fine.

**Comment by paddatrapper** [comment]
This will break the examples. The previous version assumed fx2 boards if nothing was defined, thus they did not define a board

**Comment by paddatrapper** [comment]
Fixed

**Comment by paddatrapper** [comment]
Closed, as fx2lib should be board agnostic

**Pull request closed without merging**
